name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

concurrency:
    group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.22

            - name: Download modules
              run: go mod download

            - name: go-test
              shell: bash
              run: make test

    lint:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.22

            - name: Download modules
              run: go mod download
            
            - name: diff-check
              shell: bash
              run: |-
                set -eEu
                set +o pipefail
                make diff-check

            - name: go-lint
              shell: bash
              run: make lint

            - name: zapw-logger
              shell: bash
              env:
                REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
              run: |-
                set -eEu
                set +o pipefail
                make zapcheck 2>&1 | \
                reviewdog -efm="%f:%l:%c: %m" \
                  -name="zap-logger" \
                  -reporter="github-pr-check" \
                  -filter-mode="diff_context" \
                  -fail-on-error="true" \
                  -level="error"